#include "arch_x86_32.h"

// ========================================
// x86_32 INSTRUCTION SET DEFINITIONS
// ========================================

static const instruction_def_t x86_32_arithmetic[] = {
    {"add", "Arithmetic", 2, false},
    {"sub", "Arithmetic", 2, false},
    {"mul", "Arithmetic", 1, false},
    {"div", "Arithmetic", 1, false},
    {"inc", "Arithmetic", 1, false},
    {"dec", "Arithmetic", 1, false},
    {"neg", "Arithmetic", 1, false},
    {"cmp", "Arithmetic", 2, false},
    {"adc", "Arithmetic", 2, false},
    {"sbb", "Arithmetic", 2, false},
    {"imul", "Arithmetic", 2, false},
    {"idiv", "Arithmetic", 1, false},
    {"bsf", "Arithmetic", 2, true},
    {"bsr", "Arithmetic", 2, true},
    {"bt", "Arithmetic", 2, true},
    {"btc", "Arithmetic", 2, true},
    {"btr", "Arithmetic", 2, true},
    {"bts", "Arithmetic", 2, true},
    {"daa", "Arithmetic", 0, true},
    {"das", "Arithmetic", 0, true},
    {"aaa", "Arithmetic", 0, true},
    {"aas", "Arithmetic", 0, true},
    {"aam", "Arithmetic", 0, true},
    {"aad", "Arithmetic", 0, true}
};

static const instruction_def_t x86_32_logical[] = {
    {"and", "Logical", 2, false},
    {"or", "Logical", 2, false},
    {"xor", "Logical", 2, false},
    {"not", "Logical", 1, false},
    {"test", "Logical", 2, false},
    {"shl", "Logical", 2, false},
    {"shr", "Logical", 2, false},
    {"sal", "Logical", 2, false},
    {"sar", "Logical", 2, false},
    {"rol", "Logical", 2, false},
    {"ror", "Logical", 2, false},
    {"rcl", "Logical", 2, false},
    {"rcr", "Logical", 2, false},
    {"shld", "Logical", 3, true},
    {"shrd", "Logical", 3, true},
    {"cmc", "Logical", 0, true}
};

static const instruction_def_t x86_32_data_movement[] = {
    {"mov", "Data Movement", 2, false},
    {"push", "Data Movement", 1, false},
    {"pop", "Data Movement", 1, false},
    {"xchg", "Data Movement", 2, false},
    {"lea", "Data Movement", 2, false},
    {"pushad", "Data Movement", 0, false},
    {"popad", "Data Movement", 0, false},
    {"pushfd", "Data Movement", 0, false},
    {"popfd", "Data Movement", 0, false},
    {"movzx", "Data Movement", 2, true},
    {"movsx", "Data Movement", 2, true},
    {"bswap", "Data Movement", 1, true},
    {"xadd", "Data Movement", 2, true},
    {"cmpxchg", "Data Movement", 2, true},
    {"lahf", "Data Movement", 0, true},
    {"sahf", "Data Movement", 0, true},
    {"cbw", "Data Movement", 0, true},
    {"cwde", "Data Movement", 0, true},
    {"cwd", "Data Movement", 0, true},
    {"cdq", "Data Movement", 0, true},
    {"lds", "Data Movement", 2, true},
    {"les", "Data Movement", 2, true},
    {"lfs", "Data Movement", 2, true},
    {"lgs", "Data Movement", 2, true},
    {"lss", "Data Movement", 2, true},
    {"pushf", "Data Movement", 0, true},
    {"popf", "Data Movement", 0, true}
};

static const instruction_def_t x86_32_control_flow[] = {
    {"jmp", "Control Flow", 1, false},
    {"call", "Control Flow", 1, false},
    {"ret", "Control Flow", 0, false},
    {"retf", "Control Flow", 0, false},
    {"je", "Control Flow", 1, false},
    {"jne", "Control Flow", 1, false},
    {"jz", "Control Flow", 1, false},
    {"jnz", "Control Flow", 1, false},
    {"jl", "Control Flow", 1, false},
    {"jle", "Control Flow", 1, false},
    {"jg", "Control Flow", 1, false},
    {"jge", "Control Flow", 1, false},
    {"ja", "Control Flow", 1, false},
    {"jae", "Control Flow", 1, false},
    {"jb", "Control Flow", 1, false},
    {"jbe", "Control Flow", 1, false},
    {"jc", "Control Flow", 1, false},
    {"jnc", "Control Flow", 1, false},
    {"jo", "Control Flow", 1, false},
    {"jno", "Control Flow", 1, false},
    {"js", "Control Flow", 1, false},
    {"jns", "Control Flow", 1, false},
    {"loop", "Control Flow", 1, false},
    {"loope", "Control Flow", 1, false},
    {"loopne", "Control Flow", 1, false},
    {"jecxz", "Control Flow", 1, false},
    {"jcxz", "Control Flow", 1, true},
    {"jna", "Control Flow", 1, true},
    {"jnae", "Control Flow", 1, true},
    {"jnb", "Control Flow", 1, true},
    {"jnbe", "Control Flow", 1, true},
    {"jng", "Control Flow", 1, true},
    {"jnge", "Control Flow", 1, true},
    {"jnl", "Control Flow", 1, true},
    {"jnle", "Control Flow", 1, true},
    {"jnp", "Control Flow", 1, true},
    {"jp", "Control Flow", 1, true},
    {"jpe", "Control Flow", 1, true},
    {"jpo", "Control Flow", 1, true},
    {"loopz", "Control Flow", 1, true},
    {"loopnz", "Control Flow", 1, true},
    {"sete", "Control Flow", 1, true},
    {"setne", "Control Flow", 1, true},
    {"setl", "Control Flow", 1, true},
    {"setg", "Control Flow", 1, true},
    {"seta", "Control Flow", 1, true},
    {"setae", "Control Flow", 1, true},
    {"setb", "Control Flow", 1, true},
    {"setbe", "Control Flow", 1, true},
    {"setc", "Control Flow", 1, true},
    {"setge", "Control Flow", 1, true},
    {"setle", "Control Flow", 1, true},
    {"setna", "Control Flow", 1, true},
    {"setnae", "Control Flow", 1, true},
    {"setnb", "Control Flow", 1, true},
    {"setnbe", "Control Flow", 1, true},
    {"setnc", "Control Flow", 1, true},
    {"setng", "Control Flow", 1, true},
    {"setnge", "Control Flow", 1, true},
    {"setnl", "Control Flow", 1, true},
    {"setnle", "Control Flow", 1, true},
    {"setno", "Control Flow", 1, true},
    {"setnp", "Control Flow", 1, true},
    {"setns", "Control Flow", 1, true},
    {"setnz", "Control Flow", 1, true},
    {"seto", "Control Flow", 1, true},
    {"setp", "Control Flow", 1, true},
    {"setpe", "Control Flow", 1, true},
    {"setpo", "Control Flow", 1, true},
    {"sets", "Control Flow", 1, true},
    {"setz", "Control Flow", 1, true}
};

static const instruction_def_t x86_32_system[] = {
    {"int", "System", 1, false},
    {"iret", "System", 0, false},
    {"iretd", "System", 0, false},
    {"cli", "System", 0, false},
    {"sti", "System", 0, false},
    {"clc", "System", 0, false},
    {"stc", "System", 0, false},
    {"cld", "System", 0, false},
    {"std", "System", 0, false},
    {"nop", "System", 0, false},
    {"hlt", "System", 0, false},
    {"wait", "System", 0, false},
    {"cpuid", "System", 0, true},
    {"rdtsc", "System", 0, true},
    {"wrmsr", "System", 0, true},
    {"rdmsr", "System", 0, true},
    {"into", "System", 0, true},
    {"bound", "System", 2, true},
    {"enter", "System", 2, true},
    {"leave", "System", 0, true},
    {"pusha", "System", 0, true},
    {"popa", "System", 0, true},
    {"arpl", "System", 2, true},
    {"verr", "System", 1, true},
    {"verw", "System", 1, true},
    {"clts", "System", 0, true},
    {"lmsw", "System", 1, true},
    {"smsw", "System", 1, true},
    {"lgdt", "System", 1, true},
    {"sgdt", "System", 1, true},
    {"lidt", "System", 1, true},
    {"sidt", "System", 1, true},
    {"lldt", "System", 1, true},
    {"sldt", "System", 1, true},
    {"ltr", "System", 1, true},
    {"str", "System", 1, true},
    {"lar", "System", 2, true},
    {"lsl", "System", 2, true},
    {"lock", "System", 0, true},
    {"in", "System", 2, true},
    {"out", "System", 2, true},
    {"ins", "System", 0, true},
    {"insb", "System", 0, true},
    {"insw", "System", 0, true},
    {"insd", "System", 0, true},
    {"outs", "System", 0, true},
    {"outsb", "System", 0, true},
    {"outsw", "System", 0, true},
    {"outsd", "System", 0, true},
    {"esc", "System", 1, true}
};

static const instruction_def_t x86_32_string[] = {
    {"movs", "String", 0, true},
    {"movsb", "String", 0, true},
    {"movsw", "String", 0, true},
    {"movsd", "String", 0, true},
    {"lods", "String", 0, true},
    {"lodsb", "String", 0, true},
    {"lodsw", "String", 0, true},
    {"lodsd", "String", 0, true},
    {"stos", "String", 0, true},
    {"stosb", "String", 0, true},
    {"stosw", "String", 0, true},
    {"stosd", "String", 0, true},
    {"scas", "String", 0, true},
    {"scasb", "String", 0, true},
    {"scasw", "String", 0, true},
    {"scasd", "String", 0, true},
    {"cmps", "String", 0, true},
    {"cmpsb", "String", 0, true},
    {"cmpsw", "String", 0, true},
    {"cmpsd", "String", 0, true},
    {"rep", "String", 0, true},
    {"repe", "String", 0, true},
    {"repne", "String", 0, true},
    {"repz", "String", 0, true},
    {"repnz", "String", 0, true},
    {"xlat", "String", 0, true},
    {"xlatb", "String", 0, true}
};

static const instruction_category_t x86_32_categories[] = {
    {"Arithmetic", x86_32_arithmetic, sizeof(x86_32_arithmetic)/sizeof(instruction_def_t)},
    {"Logical", x86_32_logical, sizeof(x86_32_logical)/sizeof(instruction_def_t)},
    {"Data Movement", x86_32_data_movement, sizeof(x86_32_data_movement)/sizeof(instruction_def_t)},
    {"Control Flow", x86_32_control_flow, sizeof(x86_32_control_flow)/sizeof(instruction_def_t)},
    {"System", x86_32_system, sizeof(x86_32_system)/sizeof(instruction_def_t)},
    {"String", x86_32_string, sizeof(x86_32_string)/sizeof(instruction_def_t)}
};

const arch_instruction_set_t* get_x86_32_instruction_set(void) {
    static const arch_instruction_set_t x86_32_set = {
        "x86_32", 
        x86_32_categories, 
        sizeof(x86_32_categories)/sizeof(instruction_category_t)
    };
    return &x86_32_set;
}
